-- Verificación completa de la base de datos contra create_database.sql
-- Compara tabla por tabla, columna por columna, índice por índice

-- 1. Verificar todas las tablas existentes
SELECT 'TABLAS_EXISTENTES' as tipo, TABLE_NAME as nombre, TABLE_ENGINE as engine
FROM information_schema.TABLES 
WHERE TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME;

-- 2. Verificar estructura de tabla USUARIOS
SELECT 'USUARIOS_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'usuarios'
ORDER BY ORDINAL_POSITION;

-- 3. Verificar índices de USUARIOS
SELECT 'USUARIOS_INDICES' as tipo, INDEX_NAME, COLUMN_NAME, NON_UNIQUE, INDEX_TYPE
FROM information_schema.STATISTICS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'usuarios'
ORDER BY INDEX_NAME, SEQ_IN_INDEX;

-- 4. Verificar estructura de tabla AREAS
SELECT 'AREAS_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'areas'
ORDER BY ORDINAL_POSITION;

-- 5. Verificar estructura de tabla GRUPOS
SELECT 'GRUPOS_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'grupos'
ORDER BY ORDINAL_POSITION;

-- 6. Verificar estructura de tabla GRUPO_AREAS_USUARIO
SELECT 'GRUPO_AREAS_USUARIO_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'grupo_areas_usuario'
ORDER BY ORDINAL_POSITION;

-- 7. Verificar estructura de tabla INVITACIONES_GRUPO
SELECT 'INVITACIONES_GRUPO_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'invitaciones_grupo'
ORDER BY ORDINAL_POSITION;

-- 8. Verificar estructura de tabla MIEMBROS_GRUPO
SELECT 'MIEMBROS_GRUPO_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'miembros_grupo'
ORDER BY ORDINAL_POSITION;

-- 9. Verificar estructura de tabla NOTIFICACIONES
SELECT 'NOTIFICACIONES_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'notificaciones'
ORDER BY ORDINAL_POSITION;

-- 10. Verificar estructura de tabla TAREAS (CRÍTICA)
SELECT 'TAREAS_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tareas'
ORDER BY ORDINAL_POSITION;

-- 11. Verificar índices de TAREAS
SELECT 'TAREAS_INDICES' as tipo, INDEX_NAME, COLUMN_NAME, NON_UNIQUE, INDEX_TYPE
FROM information_schema.STATISTICS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tareas'
ORDER BY INDEX_NAME, SEQ_IN_INDEX;

-- 12. Verificar estructura de tabla REPUTACION_GENERAL
SELECT 'REPUTACION_GENERAL_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'reputacion_general'
ORDER BY ORDINAL_POSITION;

-- 13. Verificar índices de REPUTACION_GENERAL
SELECT 'REPUTACION_GENERAL_INDICES' as tipo, INDEX_NAME, COLUMN_NAME, NON_UNIQUE, INDEX_TYPE
FROM information_schema.STATISTICS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'reputacion_general'
ORDER BY INDEX_NAME, SEQ_IN_INDEX;

-- 14. Verificar estructura de tabla REPUTACION_MENSUAL
SELECT 'REPUTACION_MENSUAL_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'reputacion_mensual'
ORDER BY ORDINAL_POSITION;

-- 15. Verificar estructura de tabla REPUTACION_AREA
SELECT 'REPUTACION_AREA_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'reputacion_area'
ORDER BY ORDINAL_POSITION;

-- 16. Verificar estructura de tabla REPUTACION_GRUPO
SELECT 'REPUTACION_GRUPO_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'reputacion_grupo'
ORDER BY ORDINAL_POSITION;

-- 17. Verificar estructura de tabla REPUTACION_GRUPO_GENERAL
SELECT 'REPUTACION_GRUPO_GENERAL_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'reputacion_grupo_general'
ORDER BY ORDINAL_POSITION;

-- 18. Verificar estructura de tabla HISTORIAL_REPUTACION
SELECT 'HISTORIAL_REPUTACION_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'historial_reputacion'
ORDER BY ORDINAL_POSITION;

-- 19. Verificar estructura de tabla EVIDENCIAS_TAREA
SELECT 'EVIDENCIAS_TAREA_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'evidencias_tarea'
ORDER BY ORDINAL_POSITION;

-- 20. Verificar estructura de tabla RATE_LIMIT_REPUTACION
SELECT 'RATE_LIMIT_REPUTACION_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'rate_limit_reputacion'
ORDER BY ORDINAL_POSITION;

-- 21. Verificar estructura de tabla TAREAS_ASIGNADAS
SELECT 'TAREAS_ASIGNADAS_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tareas_asignadas'
ORDER BY ORDINAL_POSITION;

-- 22. Verificar estructura de tabla TAREAS_DEPENDENCIAS
SELECT 'TAREAS_DEPENDENCIAS_COLUMNAS' as tipo, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tareas_dependencias'
ORDER BY ORDINAL_POSITION;

-- 23. Verificar todas las foreign keys
SELECT 'FOREIGN_KEYS' as tipo, 
    TABLE_NAME, 
    COLUMN_NAME, 
    CONSTRAINT_NAME, 
    REFERENCED_TABLE_NAME, 
    REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE 
WHERE TABLE_SCHEMA = DATABASE() 
    AND REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY TABLE_NAME, COLUMN_NAME;

-- 24. Verificar constraints CHECK
SELECT 'CHECK_CONSTRAINTS' as tipo, 
    CONSTRAINT_NAME, 
    TABLE_NAME, 
    CHECK_CLAUSE
FROM information_schema.CHECK_CONSTRAINTS 
WHERE TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME, CONSTRAINT_NAME;
